### PR TITLE
fix: typo in auth\schema.ts

### LINKED ISSUE #38: Typo in feature\auth\schema.ts
I found a typo in in the `feature\auth\schema.ts` file

```
const signupSchema = z.object({
  name: z.string().min(1),
  email: z.string().email(),
  password: z.string().min(6),
  gender: z.enum(["Male", "Femal", "Other"]),
});
```

Should be "Female" not "Femal"

I will be making a pull request shortly. Please assign to me.

### PR DESCRIPTION
**Pull request by kliu57**
Closes #38

### CODE REVIEW

**Comment by kliu57** [comment]
@harshmangalam I only fixed a typo in one file, I'm not sure why it shows I changed 6 files
how can I fix this?

**Comment by harshmangalam** [comment]
Can you try to take a latest pull and push again ?

**Comment by kliu57** [comment]
> Can you try to take a latest pull and push again ?

That worked

**Comment by harshmangalam** [comment]
Thanks

**Comment by harshmangalam** [comment]
Hi @kliu57 

Thank you so much for contributing to Event Blend during Hacktoberfest! Your efforts are truly appreciated, and we’d love to give you kudos and a shout-out for your amazing work.

If you're comfortable, please feel free to share your social media handles like ig,linkedin, twitter,etc... so we can tag you in our appreciation posts and spread the word about your contributions!

Looking forward to seeing you in the community. Thanks again for being awesome!

Best,
Harsh Mangalam
Maintainer, Event Blend

**Comment by kliu57** [comment]
@harshmangalam my linkedin is https://www.linkedin.com/in/liu-katie/. Glad to help!

**Comment by harshmangalam** [comment]
thanks mentioned you in my post

**Pull request merged**
