### PR TITLE
Create new api to handle Edit profile info 

### PR DESCRIPTION
**Pull request by moudgalya1223**

### CODE REVIEW

**Comment by moudgalya1223** [comment]
Please find the below patch request @harshmangalam

**Comment by harshmangalam** [comment]
do not create separate api to update name and bio instead create one api i.e /api/user/:id/edit-profile that will update name,bio

**Comment by harshmangalam** [comment]
Do not include `isAdmin` middleare otherwise only admin can update the profile but we want proflle owner should update.

**Comment by harshmangalam** [comment]
Can yoy please change `/updatename` to `/edit-profile`  ?

**Comment by moudgalya1223** [comment]
hello @harshmangalam  updated as per the requiremt , thanks

**Comment by harshmangalam** [comment]
Hi @moudgalya1223  ,

Thank you so much for contributing to Event Blend during Hacktoberfest! Your efforts are truly appreciated, and we’d love to give you kudos and a shout-out for your amazing work.

If you're comfortable, please feel free to share your social media handles like ig,linkedin, twitter,etc... so we can tag you in our appreciation posts and spread the word about your contributions!

Looking forward to seeing you in the community. Thanks again for being awesome!

Best,
Harsh Mangalam
Maintainer, Event Blend

**Comment by moudgalya1223** [comment]
Hi @moudgalya1223  here is my linkdln handle feel free to tag there www.linkedin.com/in/datta-moudgalya-bandhakavi

**Pull request merged**
